version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" # Location of Dockerfile
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"  
    schedule:
      interval: "weekly"
