module.exports = {
  allTags: async function() {
    // FIXME this should be generated by soon-to-exist Labels model... i guess?
    return ['buffalo', 'camel', 'canoe', 'car', 'cow', 'crocodile', 'eland', 'elephant', 'gazelle_grants', 'gazelle_thomsons', 'gerenuk', 'giant_forest_hog', 'giraffe', 'goat', 'hartebeest', 'hippo', 'impala', 'kob', 'kudu', 'motorcycle', 'oribi', 'oryx', 'ostrich', 'roof_grass', 'roof_mabati', 'sheep', 'topi', 'vehicle', 'warthog', 'waterbuck', 'white_bones', 'wildebeest', 'zebra'];
  },

  attributes: {
    taskId: { type: 'string', required: true },
    imageId: { type: 'string', required: true },
    queuedImageId :  { type: 'string', required: true },
    assigneeType: { type: 'string', required: true},
    assigneeDiplayName: { type: 'string', required: true},
    assignee: { type: 'string', required: true},
    wicConfidence: { type: 'number'},
    boundingBoxes : { type: 'json', columnType : "array" }
  }
};
