name: Build and upload Docker for Scout

on:
  push:
     branches:
      - main
  repository_dispatch:
    types: build-trigger

jobs:
  devops:
    name: Docker image build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        images:
          - scout

    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'push' || github.event_name =='repository_dispatch'}}
        with:
          ref: main

      - name: Free Disk space
        run: |
             sudo swapoff -a
             sudo rm -f /swapfile
             sudo rm -rf /opt/hostedtoolcache
             sudo apt clean
             if [ "$(docker image ls -aq)" ]; then
                docker rmi $(docker image ls -aq)
             else
                echo "No Docker images to remove."
             df -h

      # Build images
      - name: Build images
        run: |
          # Build Image
          bash ./build.sh ${{ matrix.images }}

      # Log into image registries
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: wildmeorg
          password: ${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub (Latest)
        if: ${{ github.event_name == 'push' || github.event_name =='repository_dispatch' }}
        run: |
          VERSION=$(echo ${GITHUB_REF} | sed 's#.*/v##')
          bash ./publish.sh -t latest ${PUBLISH_IMAGES}
        env:
          PUBLISH_IMAGES: ${{ matrix.images }} scout


